DiaryApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #url for the admin section of the website
    path('admin/', admin.site.urls),
    #The Notes app urls
    path('',include('Notes.urls')),
    #The Accounts app urls
    path('', include('Accounts.urls'))
]

Notes/urls.py
from . import views
from django.urls import path

#The app's namespace.
app_name = "Notes"

urlpatterns = [
#The url to the home page.
path('', views.HomePageView.as_view(), name = 'home_page'),
#A url mapped to a view that renders a user's diaries and new diary form.
path('mydiaries/', views.my_diaries, name = 'my_diaries'),
#A url mapped to a view that renders a user's diary content and a note form.
path('mydiaries/<diary>/', views.diary_content, name ='diary_content'),
#A url mapped to a view that deletes a user's diary on their request.
path('mydiaries/<diary>/delete/', views.delete_diary, name ='delete_diary'),
#A url mapped to a view that renders a user's note in read mode.
path('mydiaries/<diary>/<note>/delete/', views.delete_note, name='delete_note'),
#A url mapped to a view that renders a user's diaries and new diary form.
path('mydiaries/<diary>/<note>/edit/', views.note_content, name='note_content'),
#A url mapped to a view that renders a user's note content.
path('mydiaries/<diary>/<note>/read/', views.note_read_mode, name='note_read_mode'),
]

Notes/forms.py
from django import forms
from .models import Diary, Note

class DiaryForm(forms.ModelForm):
    """
    This class extends Django's ModelForm.
    This class is used for creating a form for creating user diaries.
    """
    class Meta:
        """
        An inner class that specifies the meta data of the ModelForm class.
        In this case the form's default field configurations have been Overrided.

        Attributes
        ----------
        model : obj
            Specifies the model class to be used for creating a form.
        fields : list
            Specifies the fields to be used in the form.
        """
        model = Diary
        fields = ["title"]

    def __init__(self, *args, **kwargs):
        """
        Overrides the default form widgets for modifying the form field appearance.

        Parameters
        ----------
        *args
            Non key-worded variable number arguments.
        **kwargs : dict
            Variable dictionary arguments.
        """
        super(DiaryForm, self).__init__(*args, **kwargs)

        #Changes the default form widgets appearance of every field in the form class using update()
        self.fields['title'].widget.attrs.update({'class':'form-control', 'placeholder':"Enter your diary's title here"})


class EditNoteForm(forms.ModelForm):
    """
    This class extends Django's ModelForm.
    This class is used for creating a form for editing a user's notes.
    """

    class Meta:
        """
        An inner class that specifies the meta data of the ModelForm class.
        In this case the form's default field configurations have been Overrided.

        Attributes
        ----------
        model : obj
            Specifies the model class to be used for creating a form.
        fields : list
            Specifies the fields to be used in the form.
        """
        model = Note
        fields = ["title", "content"]

    def __init__(self, *args, **kwargs):
        """
        Overrides the default form widgets for modifying the form field appearance.

        Parameters
        ----------
        *args
            Non key-worded variable number arguments.
        **kwargs : dict
            Variable dictionary arguments.
        """
        super(EditNoteForm, self).__init__(*args, **kwargs)

        #Changes the default form widgets appearance of every field in the form class using update()
        self.fields['title'].widget.attrs.update({'class':'form-control', 'placeholder':"Enter your note's title here"})
        self.fields['content'].widget.attrs.update({'class':'form-control', 'placeholder':'Enter your content here'})


class NewNoteForm(forms.ModelForm):
    """
    This class extends Django's ModelForm.
    This class is used for creating a form for creating user notes in a diary.
    """

    class Meta:
        """
        An inner class that specifies the meta data of the ModelForm class.
        In this case the form's default field configurations have been Overrided.

        Attributes
        ----------
        model : obj
            Specifies the model class to be used for creating a form.
        fields : list
            Specifies the fields to be used in the form.
        """
        model = Note
        fields = ["title"]

    def __init__(self, *args, **kwargs):
        """
        Overrides the default form widgets for modifying the form field appearance.

        Parameters
        ----------
        *args
            Non key-worded variable number arguments.
        **kwargs : dict
            Variable dictionary arguments.
        """
        super(NewNoteForm, self).__init__(*args, **kwargs)

        #Changes the default form widgets appearance of every field in the form class using update()
        self.fields['title'].widget.attrs.update({'class':'form-control', 'placeholder':"Enter your note's title here"})

Notes/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.generic import TemplateView
from Notes.forms import DiaryForm, EditNoteForm, NewNoteForm
from Notes.models import Diary, Note

class HomePageView(TemplateView):
    """
    A view that extends Django's default TemplateView.
    This view is used to render the home page to a user.

    Attributes
    ----------
    template_name : str
        The html page for the user response.
    """
    template_name = "Notes/index.html"


@login_required
def delete_diary(request, diary):
    """
    A view that deletes a user's diary.
    The diary is extracted by matching the user's diary to the diary field of the Note object.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    diary : str
        The user's diary name.

    Returns
    -------
    HttpResponseRedirect
        redirect to the my_diaries view.
    """
    my_diary = Diary.objects.get(title=diary)
    my_diary.delete()
    return redirect('Notes:my_diaries')


@login_required
def delete_note(request, diary, note):
    """
    A view that deletes a user's diary note.
    The note is extracted by matching the user's diary to the diary field of the Note object
    and the user's note to the Note title field.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    diary : str
        The user's diary name.
    note : str
        The user's note.
    Returns
    -------
    HttpResponseRedirect
        redirect to the diary_content view.
    """
    my_diary = Diary.objects.get(title=diary)
    cond1 = Q(title=note)
    cond2 = Q(diary = my_diary)
    Note.objects.get(cond1 & cond2).delete()
    return redirect('Notes:diary_content', diary=diary)


@login_required
def diary_content(request, diary):
    """
    A view that renders a user's diary content and a NewNoteForm for adding new notes.
    The notes are extracted by matching the user's diary to the diary field of the Note object.
    Duplicate note names are not allowed in the same diary of a user.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    diary : str
        The user's diary name.

    Returns
    -------
    HttpResponseRedirect
        A request to the note_content view when the user submits valid POST data and a new Note object is created.
    HttpResponse
        A new NewNoteForm instance when the user accesses the diary_content page.
        A NewNoteForm instance with errors when the user enters invalid data or enters an existing note name.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    my_diary = Diary.objects.get(title=diary)
    notes = Note.objects.filter(diary=my_diary.id).order_by('title')
    if request.method == "POST":
        form = NewNoteForm(request.POST)
        title = request.POST["title"]
        note = Note.objects.filter(title=title, diary=my_diary)
        if note:
            error_message = "This note already exists"
            form = DiaryForm()
            return render(request, 'Notes/diary_content.html', {'diary':diary, 'error_message':error_message, 'form':form, 'notes':notes})
        if form.is_valid():
            note = form.save(commit=False)
            note.diary = my_diary
            note.create_date = timezone.now()
            note.last_update_time = timezone.now()
            note.save()
            return redirect('Notes:note_content', diary=diary, note=note)
        return render(request, 'Notes/diary_content.html', {'diary':diary, 'form':form, 'notes':notes})
    else:
        form = NewNoteForm()
        return render(request, 'Notes/diary_content.html', {'diary':diary, 'form':form, 'notes':notes})


@login_required
def my_diaries(request):
    """
    A view that renders a user's diaries and a DiaryForm for adding new diaries.
    The diaries are extracted by matching the user's current username to the author field of the Diary object.
    Duplicate diary names are not allowed for a user.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.

    Returns
    -------
    HttpResponseRedirect
        A request to the diary_content view when the user submits valid POST data and a new Diary object is created.
    HttpResponse
        A new DiaryForm instance when the user accesses the mydiaries page.
        A DiaryForm instance with errors when the user enters invalid data or enters an existing diary name.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    if request.method == "POST":
        form = DiaryForm(request.POST)
        diary_title = request.POST["title"]
        author = request.user
        cond1 = Q(title=diary_title)
        cond2 = Q(author = author)
        diaries = Diary.objects.filter(cond1 & cond2)
        if diaries:
            error_message = "This diary already exists"
            form = DiaryForm()
            diaries = Diary.objects.filter(author=request.user).order_by('title')
            return render(request, 'Notes/my_diaries.html', {'form':form, 'diaries':diaries, 'error_message':error_message})
        if form.is_valid():
            diary = form.save(commit=False)
            diary.author = author
            diary.create_date = timezone.now()
            diary.save()
            return redirect('Notes:diary_content',diary=diary)
        diaries = Diary.objects.filter(author=request.user).order_by('title')
        return render(request, 'Notes/my_diaries.html', {'form':form, 'diaries':diaries})
    else:
        form = DiaryForm()
        diaries = Diary.objects.filter(author=request.user).order_by('title')
        return render(request, 'Notes/my_diaries.html', {'form':form, 'diaries':diaries})


@login_required
def note_content(request, diary ,note):
    """
    A view that renders a user's note content and a EditNoteForm for editing notes.
    The notes are extracted by matching the user's diary to the diary field of the Note object
    and the user's note to the title field of Note.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    diary : str
        The user's diary name.
    note : str
        The user's note name in the diary.

    Returns
    -------
    HttpResponseRedirect
        A request to the note_content view when the user submits valid POST data and a existing Note instance is rendered.
    HttpResponse
        A new EditNoteForm instance when the user accesses the note_content page.

    Raises
    ------
    ValidationError
        If the form data is not correct or as per guidelines.
    """
    my_diary = Diary.objects.get(title=diary)
    cond1 = Q(title=note)
    cond2 = Q(diary = my_diary)
    note = Note.objects.get(cond1 & cond2)
    if request.method == "POST":
        form = EditNoteForm(request.POST, instance=note)
        if form.is_valid():
            note = form.save(commit=False)
            note.last_update_time=timezone.now()
            note.save()
            return redirect('Notes:note_content', diary=diary, note=note)
    form = EditNoteForm(instance=note)
    return render(request, 'Notes/notes_content.html', {'diary':diary, 'form':form, 'note':note})


@login_required
def note_read_mode(request, diary, note):
    """
    A view that renders a user's note content in read mode.
    The notes are extracted by matching the user's diary to the diary field of the Note object
    and the user's note to the title field of Note.
    This view can only be accessed if a user is authenticated.
    The login_required decorator is used to ensure the previous point.

    Parameters
    ----------
    request : HttpRequest object
        An HttpRequest object that contains metadata about a request.
    diary : str
        The user's diary name.
    note : str
        The user's note name in the diary.

    Returns
    -------
    HttpResponse
        A new EditNoteForm instance when the user accesses the note_content page.
    """
    my_diary = Diary.objects.get(title=diary)
    cond1 = Q(title=note)
    cond2 = Q(diary = my_diary)
    note = Note.objects.get(cond1 & cond2)
    return render(request, 'Notes/notes_content.html', {'diary':diary, 'note':note})

Notes/templates/Notes/diary_content.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-2">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'Notes:my_diaries' %}">MyDiaries</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{diary.title}}</li>
        </ol>
        <div class = "row justify-content-center">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#createNote" class="nav-link active" data-toggle="tab">Create Note</a>
                </li>
                <li class="nav-item">
                    <a href="#viewNotes" class="nav-link" data-toggle="tab">View Notes</a>
                </li>
                <li class="nav-item">
                    <a href="#deleteDiary" class="nav-link" data-toggle="tab">Delete Diary</a>
                </li>
            </ul>
        </div>
        <div class="row justify-content-center align-items-center mt-2">
            <div class="col-xl-8">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="createNote">
                        <div class="card">
                            <div class="card-header text-center form-background-color">
                                <h1 class="text-white">Create Note<h1>
                            </div>
                            <div class="card-body form-background-color">
                                {% if error_message %}
                                    <div class="text-center text-danger">
                                        <h5>{{error_message}}</h5>
                                    </div>
                                {% endif %}
                                <form action="{% url 'Notes:diary_content' diary=diary %}" method="POST" novalidate>
                                {% csrf_token %}
                                    <div class="form-group">
                                        {{form.title}}
                                        <small class="text-danger">{{form.title.errors|striptags}}</small>
                                    </div>
                                    <div class = "form-group text-center">
                                        <button type="submit" class="btn">Create Note</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="viewNotes">
                        <div class="row justify-content-center">
                            <div class="col-xl-8">
                                <div class="card">
                                    <div class="card-header text-center form-background-color">
                                        <h1 class="text-white">{{diary.title}}<h1>
                                    </div>
                                    {% if notes %}
                                    <div class="card-body form-background-color">
                                        <div class="form-group">
                                            {% for note in notes %}
                                                <div class=" text-center form-group">
                                                    <a class="btn btn-block note-btn-color" href="{% url 'Notes:note_content' note=note diary=diary %}" role="button">{{note.title}}</a>
                                                    <small class="text-white">Last updated on {{note.last_update_time}}</small>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="deleteDiary">
                        <div class="form-group text-center">
                            <a class="btn btn-danger" data-toggle="modal" data-target="#staticBackdrop" role="button">Delete Diary</a>
                        </div>
                    </div>
                    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Danger</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                  Are you sure you want to delete <strong>{{diary.title}}<strong>?
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-purple" href="{% url 'Notes:delete_diary' diary=diary %}" role="button">Yes</a>
                                    <a class="btn btn-purple" data-dismiss="modal" role="button">No</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Notes/templates/Notes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="card-deck">
                <div class="card  form-background-color">
                    <div class="card-header text-center form-background-color">
                      <h2 class="card-title text-center">Access your <strong class="text-purple">notes</strong> from <strong class="text-purple">anywhere</strong></h2>
                    </div>
                    <div class="card-body text-white">
                        <img class="card-img" src="{% static 'images/access_anywhere.jpg' %}" alt="Card image cap">
                    </div>
                </div>
                <div class="card form-background-color">
                    <div class="card-header text-center form-background-color">
                        <h2 class="card-title text-center"><strong class="text-purple">Ubiquitous Diaries</strong> is <strong class="text-purple">Free</strong></h2>
                    </div>
                    <div class="card-body text-white">
                      <img class="card-img" src="{% static 'images/happy_person.png' %}" alt="Card image cap">
                    </div>
                </div>
                <div class="card form-background-color">
                    <div class="card-header text-center form-background-color">
                        <h2 class="card-title text-center"><strong class="text-purple">Maximize</strong> your <strong class="text-purple">productivity</strong> with us</h2>
                    </div>
                    <div class="card-body text-white">
                      <img class="card-img" src="{% static 'images/productivity.jpg' %}" alt="Card image cap">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Notes/templates/Notes/my_diaries.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-2">
        <div class = "row justify-content-center">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a href="#createDiary" class="nav-link active" data-toggle="tab">Create Diary</a>
                    </li>
                    <li class="nav-item">
                        <a href="#viewDiaries" class="nav-link" data-toggle="tab">View Diaries</a>
                    </li>
                </ul>
        </div>
        <div class="row justify-content-center mt-2">
            <div class="col-xl-8">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="createDiary">
                        <div class="card">
                            <div class="card-header text-center form-background-color">
                                <h1 class="text-white">Create Diary<h1>
                            </div>
                            <div class="card-body form-background-color">
                                {% if error_message %}
                                    <div class="text-center text-danger">
                                        <h5>{{error_message}}</h5>
                                    </div>
                                {% endif %}
                                <form action="{% url 'Notes:my_diaries' %}" method="POST" novalidate>
                                {% csrf_token %}
                                    <div class="form-group">
                                        {{form.title}}
                                        <small class="text-danger">{{form.title.errors|striptags}}</small>
                                    </div>
                                    <div class = "form-group text-center">
                                        <button type="submit" class="btn">Create Diary</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="viewDiaries">
                        <div class="row justify-content-center align-items-center mt-2">
                            <div class="col-xl-8">
                                <div class="card">
                                    <div class="card-header text-center form-background-color">
                                        <h1 class="text-white">My Diaries<h1>
                                    </div>
                                    <div class="card-body form-background-color">
                                        {% for diary in diaries %}
                                            <div class="form-group text-center">
                                                <a class="btn btn-block diary-btn-color" href="{% url 'Notes:diary_content' diary=diary %}" role="button">{{diary.title}}</a>
                                                <small class="text-white">Created on {{diary.create_date}}</small>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Notes/templates/Notes/notes_content.html
{% extends 'base.html' %}

{% block content %}
    <div class = "container mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'Notes:my_diaries' %}">MyDiaries</a></li>
                <li class="breadcrumb-item"><a href="{% url 'Notes:diary_content' diary=diary%}">{{diary.title}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{note.title}}</li>
            </ol>
        </nav>
        <div class="row justify-content-center">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#editNote" class="nav-link active" data-toggle="tab">Edit Note</a>
                </li>
                <li class="nav-item">
                    <a href="#readNote" class="nav-link" data-toggle="tab">Read Note</a>
                </li>
                <li class="nav-item">
                    <a href="#deleteNote" class="nav-link" data-toggle="tab">Delete Note</a>
                </li>
            </ul>
        </div>
        <div class="row justify-content-center mt-2">
            <div class="col-xl-8">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="editNote">
                        <div class="card">
                            <div class="card-header text-center form-background-color">
                                <h1 class="text-white">{{note.title}}<h1>
                            </div>
                            <div class="card-body form-background-color">
                                <form action="{% url 'Notes:note_content' diary=diary note=note %}" method="POST" novalidate>
                                {% csrf_token %}

                                    <div class="form-group">
                                        {{ form.title }}
                                        <small class="text-danger">{{ form.errors.title|striptags}}</small>
                                    </div>
                                    <div class="form-group">
                                        {{ form.media }}
                                        {{ form.content }}
                                        <small class="text-danger">{{ form.errors.content|striptags}}</small>
                                    </div>
                                    <div class="row justify-content-center align-items-center">
                                        <div class = "col-xl-6">
                                            <div class="form-group text-center">
                                                <button type="submit" class="btn btn-block">Save</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="readNote">
                        <div class="card">
                            <div class="card-header text-center form-background-color">
                                <h1 class="text-white">{{note.title}}<h1>
                            </div>
                            <div class="card-body">
                                {{note.content|safe}}
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="deleteNote">
                        <div class="form-group text-center">
                            <a class="btn btn-danger" data-toggle="modal" data-target="#staticBackdrop" role="button">Delete Note</a>
                        </div>
                    </div>
                    <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Danger</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete <strong>{{note.title}}<strong>?
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-purple" data-dismiss="modal" role="button">No</a>
                                    <a class="btn btn-purple" href="{% url 'Notes:delete_note' diary=diary note=note %}" role="button">Yes</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}