Accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from Accounts.forms import SignInForm, ForgotPasswordForm, NewPasswordForm, ChangePasswordForm
from django.urls import reverse_lazy

#Namespace for the Accounts app.
app_name = 'Accounts'

urlpatterns = [
    #A url mapped to a view that generates an email confirmation request.
    path('email_confirmation/<uidb64>/<token>/',views.email_confirmation, name='email_confirmation'),
    #A url mapped to a view that renders the user's my account page.
    path('myaccount/', views.myaccount, name = 'myaccount'),
    #A url mapped to a view that renders a password change page for signed in users.
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='Accounts/password_change_form.html', form_class=ChangePasswordForm, success_url=reverse_lazy('Accounts:password_change_done')), name='password_change'),
    #A url mapped to a view that generates a response when a signed in user changes their password.
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='Accounts/password_change_done.html'), name='password_change_done'),
    #A url mapped to a view that renders the reset password page.
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='Accounts/password_reset.html', success_url=reverse_lazy('Accounts:password_reset_done'),form_class=ForgotPasswordForm, email_template_name='Accounts/password_reset_email.html', subject_template_name='Accounts/password_reset_subject.txt'), name='password_reset'),
    #A url mapped to a view that renders a response on a user's request to reset their password on the reset password page.
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Accounts/password_reset_done.html'), name='password_reset_done'),
    #A url mapped to a view that generates a reset password link that is emailed to the user's email address.
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Accounts/password_reset_confirm.html", form_class=NewPasswordForm, success_url=reverse_lazy('Accounts:password_reset_complete')), name='password_reset_confirm'),
    #A url mapped to a view that renders a message when the user opens the reset password link.
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='Accounts/password_reset_complete.html'), name='password_reset_complete'),
    #A url mapped to a view that renders the signin page.
    path('signin/', auth_views.LoginView.as_view(template_name='Accounts/signin.html', authentication_form=SignInForm, redirect_field_name="Notes/my_diaries.html"), name = 'login'),
    #A url mapped to a view that handles a user signout.
    path('signout/', auth_views.LogoutView.as_view(), name = 'logout'),
    #A url mapped to a view that renders the signup page.
    path('signup/', views.signup, name = 'signup'),
    #A url mapped to a view that renders a response when a user confirms their email address.
    path('signup/complete/',views.SignUpCompleteView.as_view(), name='signup_complete'),
    #A url mapped to a view that renders a response when a user signs up.
    path('signup/done/',views.SignUpDoneView.as_view(), name='signup_done'),
    #A url mapped to a view that renders a forgot username page.
    path('username_send/', views.send_username, name='send_username'),
    #A url mapped to a view that renders a response when a user's username is emailed to their email address.
    path('username_send_done/',views.SendUsernameDoneView.as_view(), name='send_username_done'),
]

DiaryApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #url for the admin section of the website
    path('admin/', admin.site.urls),
    #The Notes app urls
    path('',include('Notes.urls')),
    #The Accounts app urls
    path('', include('Accounts.urls'))
]

Notes/urls.py
from . import views
from django.urls import path

#The app's namespace.
app_name = "Notes"

urlpatterns = [
#The url to the home page.
path('', views.HomePageView.as_view(), name = 'home_page'),
#A url mapped to a view that renders a user's diaries and new diary form.
path('mydiaries/', views.my_diaries, name = 'my_diaries'),
#A url mapped to a view that renders a user's diary content and a note form.
path('mydiaries/<diary>/', views.diary_content, name ='diary_content'),
#A url mapped to a view that deletes a user's diary on their request.
path('mydiaries/<diary>/delete/', views.delete_diary, name ='delete_diary'),
#A url mapped to a view that renders a user's note in read mode.
path('mydiaries/<diary>/<note>/delete/', views.delete_note, name='delete_note'),
#A url mapped to a view that renders a user's diaries and new diary form.
path('mydiaries/<diary>/<note>/edit/', views.note_content, name='note_content'),
#A url mapped to a view that renders a user's note content.
path('mydiaries/<diary>/<note>/read/', views.note_read_mode, name='note_read_mode'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Ubiquitous Diaries</title>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <link rel="shortcut icon"  href="{% static 'images/logo.ico' %}">
        <link rel = "stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div id="page-container">
            <div id="content-wrap">
                <nav class = "navbar navbar-expand-lg navbar-custom">
                    <a class = "navbar-brand" href = "{% url 'Notes:home_page' %}"><img src = "{% static 'images/logo.png' %}" height = "50px" width = "50px"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span  role="button" ><i class="fa fa-bars" aria-hidden="true"></i></span>
                    </button>
                    <div class = "collapse navbar-collapse justify-content-end" id = "navbarToggle">
                        <ul class = "navbar-nav">
                            <li class = "nav-item">
                                <a class = "nav-link" href = "{% url 'Notes:home_page' %}">Home <i class="fas fa-home fa-lg"></i></a>
                            </li>
                            {% if not user.is_authenticated %}
                                <li class = "nav-item">
                                    <a class = "nav-link" href = "{% url 'Accounts:signup' %}">Sign Up <i class="fas fa-user-plus fa-lg"></i></a>
                                </li>
                                <li class = "nav-item">
                                    <a class = "nav-link" href = "{% url 'Accounts:login' %}">Sign In <i class="fas fa-sign-in-alt fa-lg"></i></a>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class = "nav-item">
                                    <a class = "nav-link" href="{% url 'Notes:my_diaries' %}">My Diaries <i class="fas fa-book fa-lg"></i></a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      Hi {{request.user.first_name}} <i class="fas fa-user-circle fa-lg"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                      <a class = "dropdown-item" href="{% url 'Accounts:myaccount' %}">My Account <i class="fas fa-user-circle fa-lg"></i></a>
                                      <a class = "dropdown-item" href="{% url 'Accounts:logout' %}">Sign Out <i class="fas fa-sign-out-alt fa-lg"></i></a>
                                    </div>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
                {% block content %}
                {% endblock %}
                </div>
            <footer id="footer">
                <div class="container mt-3">
                    <small>&#169; 2020 Ubiquitous Diaries</small>
                </div>
            </footer>
            </div>
    </body>
</html>